### ISSUE TITLE
Visual could not be instanciated

### ISSUE THREAD

**Issue by Blumi** [microsoft/powerbi-visuals-webpack-plugin#16]
I just tried to get a custom visual loading by Power BI several times. The embedded JS gets loaded, but the visual class could not be found at runtime.
The Exception Message is "Cannot read property 'myVisual530397A454264B59BCC98231C7453345' of undefined".

When I compare the JS generated from the PBIVIZ tools and this webpack visual, it seems the following vital part is missing:

```
var powerbi;
!function (e) {
	var t;
	!function (t) {
		var n;
		!function (t) {
			t.myVisual530397A454264B59BCC98231C7453345= {
				name: "myVisual530397A454264B59BCC98231C7453345",
				displayName: "myVisual for Power BI",
				"class": "Visual",
				version: "1.0.0",
				apiVersion: "1.13.0",
				create: function (t) {
					return new e.extensibility.visual.myVisual530397A454264B59BCC98231C7453345.Visual(t)
				},
				custom: !0
			}
		}(n = t.plugins || (t.plugins = {}))
	}(t = e.visuals || (e.visuals = {}))
}(powerbi || (powerbi = {}));

```

What am I doing wrong?

**Comment by Blumi** [comment]
Ok, I got it:

- webpack entry point must be `'./.tmp/precompile/visualPlugin.ts'`
- PowerBICustomVisualsWebpackPlugin-options must contain `visualSourceLocation: "../../src/index.ts"` (or whatever path your normal entry point would have been)

**Comment by zBritva** [comment]
@Blumi did you test your changes in powerbi-visuals-tools?
The tools use this plugin to build visual too. Any changes in this package should reflect in tools to

**Comment by Blumi** [comment]
@zBritva No and I don't see how powerbi-visuals-tools relates to powerbi-visuals-webpack-plugin code-wise. Both packages seem to compile fine on their own.

Most of my changes are in the README.md.

**Comment by zBritva** [comment]
@Blumi Now, tools just wraps webpack config with the plugin:
https://github.com/Microsoft/PowerBI-visuals-tools/blob/dev/next/lib/WebPackWrap.js#L133

You can do the same with a pure webpack project.

Your PR looks good, please, resolve one conflict. I will check the plugin with tools late.
Thanks!
