### ISSUE TITLE
Getting ChunkLoadError from WebPack.

### ISSUE THREAD

**Issue by twastvedt** [microsoft/powerbi-visuals-webpack-plugin#42]
I have what I think is a paths issue, but I'm new to WebPack and a bit lost. I'm using this library because I'm trying to load a WebAssembly library into a visual. Compiling works, but the visual throws two "ChunkLoadError"s, for chunk 0 and chunk 1. I can direct the browser to "https://localhost:8080/assets/0" (or ...1) just fine. The request url that WebPack attempts though is "https://app.powerbi.com/13.0.11428.218/assets/0". I'm not sure how to either change the address requested, or make that address work, or even which of those to attempt.

Here's my webpack.config.js, only slightly modified from the example in the Readme:
```
const path = require("path");
const fs = require("fs");

// werbpack plugin
const webpack = require("webpack");

console.log(require.resolve("powerbi-visuals-webpack-plugin"));
const PowerBICustomVisualsWebpackPlugin = require("powerbi-visuals-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const Visualizer = require("webpack-visualizer-plugin");
const ExtraWatchWebpackPlugin = require("extra-watch-webpack-plugin");

// api configuration
const powerbiApi = require("powerbi-visuals-api");

// visual configuration json path
const pbivizPath = "./pbiviz.json";
const pbivizFile = require(path.join(__dirname, pbivizPath));

// the visual capabilities content
const capabilitiesPath = "./capabilities.json";
const capabilitiesFile = require(path.join(__dirname, capabilitiesPath));

const pluginLocation = "./.tmp/precompile/visualPlugin.ts"; // path to visual plugin file, the file generates by the plugin

// string resources
// Disable resources for now.
// const resourcesFolder = path.join(".", "stringResources");
// const localizationFolders = fs.readdirSync(resourcesFolder);
const localizationFolders = [];
const resourcesFolder = ".";

// babel options to support IE11
const babelOptions = {
    presets: [
        [
            require.resolve("@babel/preset-env"),
            {
                targets: {
                    ie: "11",
                },
                useBuiltIns: "entry",
                modules: false,
                corejs: "3",
            },
        ],
    ],
    sourceType: "unambiguous", // tell to babel that the project can contains different module types, not only es2015 modules
    cacheDirectory: path.join(".tmp", "babelCache"), // path for chace files
};

module.exports = {
    entry: {
        "visual.js": pluginLocation,
    },
    target: "web",
    node: {
        fs: "empty",
    },
    optimization: {
        concatenateModules: false,
        // minimize: true, // enable minimization for create *.pbiviz file less than 2 Mb, can be disabled for dev mode
    },
    devtool: "source-map",
    mode: "development",
    module: {
        rules: [
            {
                parser: {
                    amd: false,
                },
            },
            {
                test: /(\.ts)x|\.ts$/,
                include: /powerbi-visuals-|src|precompile\\visualPlugin.ts/,
                use: [
                    {
                        loader: require.resolve("babel-loader"),
                        options: babelOptions,
                    },
                    {
                        loader: require.resolve("ts-loader"),
                        options: {
                            transpileOnly: false,
                            experimentalWatchApi: false,
                        },
                    },
                ],
            },
            {
                test: /(\.js)x|\.js$/,
                use: [
                    {
                        loader: require.resolve("babel-loader"),
                        options: babelOptions,
                    },
                ],
            },
            {
                test: /\.json$/,
                loader: require.resolve("json-loader"),
                type: "javascript/auto",
            },
            {
                test: /\.less$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: require.resolve("css-loader"),
                    },
                    {
                        loader: require.resolve("less-loader"),
                        options: {
                            paths: [path.resolve(__dirname, "..", "node_modules")],
                        },
                    },
                ],
            },
            {
                test: /\.css$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: require.resolve("css-loader"),
                    },
                ],
            },
            {
                test: /\.(woff|ttf|ico|woff2|jpg|jpeg|png|webp)$/i,
                use: [
                    {
                        loader: "base64-inline-loader",
                    },
                ],
            },
        ],
    },
    resolve: {
        extensions: [".wasm", ".tsx", ".ts", ".jsx", ".js", ".css", ".3dm"],
    },
    output: {
        path: path.join(__dirname, "/.tmp", "drop"),
        publicPath: "/assets/",
        filename: "[name]",
    },
    devServer: {
        disableHostCheck: true,
        contentBase: path.join(__dirname, ".tmp", "drop"), // path with assets for dev server, they are generated by webpack plugin
        compress: true,
        port: 8080, // dev server port
        hot: false,
        inline: false,
        // cert files for dev server
        https: {
            // key: path.join(__dirname, "certs","PowerBICustomVisualTest_public.key"), // for darwin, linux
            // cert: path.join(__dirname, "certs", "PowerBICustomVisualTest_public.cer"), // for darwin, linux
            pfx: fs.readFileSync(path.join(__dirname, "node_modules/powerbi-visuals-tools/certs/PowerBICustomVisualTest_public.pfx")), // for windows
            passphrase: "##########",
        },
        headers: {
            "access-control-allow-origin": "*",
            "cache-control": "public, max-age=0",
        },
    },
    externals: {
        "powerbi-visuals-api": "null",
        fakeDefine: "false",
        corePowerbiObject: "Function('return this.powerbi')()",
        realWindow: "Function('return this')()",
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: "visual.css",
            chunkFilename: "[id].css",
        }),
        new Visualizer({
            filename: "webpack.statistics.dev.html",
        }),
        // visual plugin regenerates with the visual source, but it does not require relaunching dev server
        new webpack.WatchIgnorePlugin([
            path.join(__dirname, pluginLocation),
            "./.tmp/**/*.*",
        ]),
        // custom visuals plugin instance with options
        new PowerBICustomVisualsWebpackPlugin({
            ...pbivizFile,
            capabilities: capabilitiesFile,
            stringResources: localizationFolders.map((localization) => path.join(
                resourcesFolder,
                localization,
                "resources.resjson",
            )),
            apiVersion: powerbiApi.version,
            capabilitiesSchema: powerbiApi.schemas.capabilities,
            pbivizSchema: powerbiApi.schemas.pbiviz,
            stringResourcesSchema: powerbiApi.schemas.stringResources,
            dependenciesSchema: powerbiApi.schemas.dependencies,
            devMode: true,
            generatePbiviz: false,
            generateResources: true,
            modules: true,
            visualSourceLocation: "../../src/visual",
            pluginLocation,
            packageOutPath: path.join(__dirname, "dist"),
        }),
        new ExtraWatchWebpackPlugin({
            files: [
                pbivizPath,
                capabilitiesPath,
            ],
            dirs: [
                "assets",
            ],
        }),
        new webpack.ProvidePlugin({
            window: "realWindow",
            define: "fakeDefine",
            powerbi: "corePowerbiObject",
        }),
    ],
};
```

**Comment by twastvedt** [comment]
Progress maybe? I changed `output[publicPath]` in my config to "https://localhost:8080/assets/". It seems that prevented WebPack from prepending the script source with "https://app.powerbi.com/13.0.11428.218". I'm now only getting an error for loading chunk 1, and in the browser dev tools I can see that both chunks were successfully downloaded. Not sure where to go from here though.

**Comment by twastvedt** [comment]
I don't think this was an issue with this repository. Looks like Webpack has some work to do to make Emscripten work nicely (https://github.com/webpack/webpack/issues/7352). I posted some of what I did to get this to work here: https://stackoverflow.com/questions/58979629/why-is-webpack-failing-to-load-chunks/59201577#59201577.

**Comment by LasanthaKathriarachchi** [comment]
Hi Guys...

I came across 3 errors while working on a tab pane rendering in custom visual.
Its entry level Vue module as below. It has 3 dynamic loading of components.

----------------------------
<template>
  <ModalComponent v-if="ui.activeModal" @close-modal="ui.setModal(null)" />
  <buttonBar />
  <SidePane @collapse="ui.switchSidePane()" :is-open="ui.sidePane">
    <KeepAlive>
      <component :is="tabs[ui.activeTab]"></component>
    </KeepAlive>
  </SidePane>
  <AppMap />
</template>

<script setup lang="ts">

import { computed, defineAsyncComponent, defineComponent } from "vue";
import AppMap from "./components/AppMap.vue";
import SidePane from "./components/SidePane/SidePane.vue";
import buttonBar from "./components/buttonBar.vue";
import ModalComponent from "./components/ModalWindows/ModalComponent.vue";
import { useUiStore } from "./stores/ui-store";

const ui = useUiStore();

const tabs: any = {
  BaseMaps: defineAsyncComponent(() => import("./components/BaseMaps.vue")),
  GeoToolbox: defineAsyncComponent(() => import("./components/GeoToolbox.vue")),
  DataManager: defineAsyncComponent(() => import("./components/DataManager/DataManager.vue")),
};

</script>
----------------------------

**I got these 3 errors while clicking on each tab of tab pane**.

ChunkLoadError: Loading chunk vendors-node_modules_colorbrewer_index_es_js-node_modules_css-loader_dist_cjs_js_node_modules-16d10c failed.

ChunkLoadError: Loading chunk src_components_GeoToolbox_vue failed.

ChunkLoadError: Loading chunk src_components_BaseMaps_vue failed.


**These are the relevant settings in webpack.config.js**

------------------------------------------
output: {
        path: path.join(__dirname, "/.tmp", "drop"),
        publicPath: '/assets/',
        chunkFilename: "[name].js",
        filename: "visual.js",
        library: +powerbiApi.version.replace(/\./g, "") >= 320 ? pbivizFile.visual.guid : undefined,
        libraryTarget: +powerbiApi.version.replace(/\./g, "") >= 320 ? 'var' : undefined,
    } 
---------------------------------------------
module: {
        rules: [
            {
                test: /module\.js$/,
                loader: "exports-loader",
            },
            {
                test: /module\.wasm$/,
                type: "javascript/auto",
                loader: "file-loader",
            }
       ]
    }
------------------------------------
plugins: [
new MiniCssExtractPlugin({
            filename: "visual.css",
            chunkFilename: "[name].css"
        })
]
--------------------------------------

Any body know the reason why the "ChunkLoadError".
Please advise.

Thanks in advance..

**Comment by luizzappa** [comment]
How did you manage to get past the "Content Security Policy. The `wam` file is served by localhost, but it seems to me that app.powerbi.com blocks (?)

![image](https://github.com/microsoft/powerbi-visuals-webpack-plugin/assets/65685842/e60cb7d5-2c5b-4841-a444-3bf03d0fafdd)

**Comment by AleksSavelev** [comment]
Hello @luizzappa,

Try to add these lines in your `privileges` inside of capabilities.json:
```json
"privileges": [
    {
      "name": "WebAccess",
      "parameters": ["*"]
    }
  ]
```

**Comment by luizzappa** [comment]
perfect @AleksSavelev !
