### ISSUE TITLE
Support Webpack 5 

### ISSUE THREAD

**Issue by davidmartin** [microsoft/powerbi-visuals-webpack-plugin#72]
Hi Team !! I'm trying to use this plugin with webpack 5 but I'm getting this error when starting the webpack server.

I followed your `README.md` steps and changed everything in `webpack.config.js` to make it work with webpack 5.

### Error log:
```shell
> circle-card-react@1.0.1 start
> webpack server

(node:41412) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
<i> [webpack-dev-server] SSL certificate: Webpack-5/node_modules/.cache/webpack-dev-server/server.pem
 info   Start preparing plugin template
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): https://192.168.0.13:8080/
<i> [webpack-dev-server] On Your Network (IPv6): https://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from 'Webpack-5/.tmp/drop' directory
 info   Finish preparing plugin template
 info   Start packaging...
 info   Package compression enabled
 info   Package created!
 info   Finish packaging
 info   Need additional run
/Webpack-5/node_modules/webpack/lib/NormalModule.js:1313
                const size = Math.max(1, this.generator.getSize(this, type));
                                                        ^

TypeError: Cannot read properties of undefined (reading 'getSize')
    at NormalModule.size (Webpack-5/node_modules/webpack/lib/NormalModule.js:1313:43)
    at _ (Webpack-5/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js:1092:18)
    at Webpack-5/node_modules/webpack/lib/stats/DefaultStatsFactoryPlugin.js:2320:9
    at Hook.eval [as call] (eval at create (Webpack-5/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (Webpack-5/node_modules/tapable/lib/Hook.js:14:14)
    at Webpack-5/node_modules/webpack/lib/stats/StatsFactory.js:278:7
    at StatsFactory._forEachLevel (Webpack-5/node_modules/webpack/lib/stats/StatsFactory.js:101:19)
    at StatsFactory._create (Webpack-5/node_modules/webpack/lib/stats/StatsFactory.js:277:9)
    at StatsFactory.create (Webpack-5/node_modules/webpack/lib/stats/StatsFactory.js:138:16)
    at Webpack-5/node_modules/webpack/lib/stats/StatsFactory.js:216:24
```

### Dependencies: 

  "dependencies": {
    "@babel/runtime": "^7.18.3",
    "@babel/runtime-corejs3": "^7.18.3",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.7",
    "core-js": "^3.22.8",
    "powerbi-visuals-api": "^2.6.2",
    "powerbi-visuals-utils-dataviewutils": "2.0.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.18.2",
    "@babel/preset-env": "^7.18.2",
    "babel-loader": "^8.2.5",
    "base64-inline-loader": "^2.0.1",
    "css-loader": "^6.7.1",
    "extra-watch-webpack-plugin": "^1.0.3",
    "json-loader": "^0.5.7",
    "less": "^4.1.2",
    "less-loader": "^11.0.0",
    "mini-css-extract-plugin": "^2.6.0",
    "powerbi-visuals-tools": "^4.0.3",
    "powerbi-visuals-webpack-plugin": "^3.0.0",
    "ts-loader": "^9.3.0",
    "tslint": "^5.1.0",
    "tslint-microsoft-contrib": "^6.2.0",
    "typescript": "^3.8.3",
    "webpack": "^5.73.0",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.9.1"
  }
  
  
  Could you help us to get support for webpack 5 so we can continue building our React components for Power BI 😊

**Comment by AleksSavelev** [comment]
New version was published. It supports webpack 5. 
Could you please check if the issue still exists? @davidmartin

**Comment by davidmartin** [comment]
It works Thank you I close the issue
