### ISSUE TITLE
Update ts-loader and typescript to the newest version to prevent errors with the newest @types/node

### ISSUE THREAD

**Issue by ElPrudi** [microsoft/powerbi-visuals-webpack-plugin#77]
The current versions of ts-loader (6.1.0) and typescript (3.6.3) of the template return multiple errors (14 in total) with the newest types/node. For example:
```
    ERROR in C:\Dev\VSCode\Power BI\circleCard\node_modules\@types\node\assert.d.ts
        [tsl] ERROR in C:\Dev\VSCode\Power BI\circleCard\node_modules\@types\node\assert.d.ts(733,60)
      	TS1005: ';' expected.
```
This is a typescript problem which has been fixed in 3.8.0. Update ts-loader and typescript to the newest version to prevent this.

**Comment by AleksSavelev** [comment]
It's fixed in the new version of the plugin.
