### ISSUE TITLE
Receiving TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by visualphyzx** [microsoft/powerbi-visuals-webpack-plugin#86]
I'm using Webpack 5 to package pbiviz file but receiving the following error:

```
 info   Start packaging...
(node:12952) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:12952) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
(node:12952) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
 info   Package compression enabled
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2168:5)
    at go$writeFile (C:\{folder}\node_modules\graceful-fs\graceful-fs.js:138:14)
    at Object.writeFile (C:\{folder}\node_modules\graceful-fs\graceful-fs.js:135:12)
    at C:\{folder}\node_modules\powerbi-visuals-webpack-plugin\node_modules\fs-extra\lib\output\index.js:18:27
    at C:\L{folder}\node_modules\powerbi-visuals-webpack-plugin\node_modules\universalify\index.js:21:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}


Node.js v18.14.0
```

What I did was:
1. Creating a new visual using "pbiviz new" command. 
2. Follow the readme instructions. 
3. Update webpack.config.js for Webpack 5 - update WatchIgnorePlugin paths

```
 new webpack.WatchIgnorePlugin(           
  {paths: [
      path.join(__dirname, pluginLocation),
      "./.tmp/**/*.*"
  ]}
),
```
I have also tried the same process on a couple custom visuals but same error message.

Thanks for any support!!

**Comment by dm-p** [comment]
I'm getting exactly the same problem and error message as above. I had to make a couple of additional changes to the webpack config in addition to the `WatchIgnorePlugin` paths:

* `devServer.disableHostCheck = true` needed to be replaced with `devServer.allowedHosts = 'all'`, 

* `devServer.contentBase = path.join(__dirname, ".tmp", "drop")` had to be updated to `devServer.static = path.join(__dirname, ".tmp", "drop")`

If this is wrong, can you folks please share a sample repo with working setup, just so we can cross-check things like dependencies and other potential gotchas?

**Comment by AleksSavelev** [comment]
Thank you for this issue and information. Readme was updated to include this fix
